// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Ue9-x1uaP7hnB3MZWy2Y8Hc3TDrk1EA',
    appId: '1:368352443079:web:f092a012897d0b48f15ce2',
    messagingSenderId: '368352443079',
    projectId: 'pomodorable-26n09',
    authDomain: 'pomodorable-26n09.firebaseapp.com',
    storageBucket: 'pomodorable-26n09.appspot.com',
    measurementId: 'G-T44QD71LNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYjaFhpjbyO_2B4wVsFCPgEt4CoOzTlWA',
    appId: '1:368352443079:android:f5591b77c21feb8bf15ce2',
    messagingSenderId: '368352443079',
    projectId: 'pomodorable-26n09',
    storageBucket: 'pomodorable-26n09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7XrIcny6MzjIPG865DqZDLi_0DKUIB4o',
    appId: '1:368352443079:ios:f7f6c16c8fe06a4ff15ce2',
    messagingSenderId: '368352443079',
    projectId: 'pomodorable-26n09',
    storageBucket: 'pomodorable-26n09.appspot.com',
    iosBundleId: 'com.trucnguyen.myFirstFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7XrIcny6MzjIPG865DqZDLi_0DKUIB4o',
    appId: '1:368352443079:ios:f7f6c16c8fe06a4ff15ce2',
    messagingSenderId: '368352443079',
    projectId: 'pomodorable-26n09',
    storageBucket: 'pomodorable-26n09.appspot.com',
    iosBundleId: 'com.trucnguyen.myFirstFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9Ue9-x1uaP7hnB3MZWy2Y8Hc3TDrk1EA',
    appId: '1:368352443079:web:cf5d728585ec2482f15ce2',
    messagingSenderId: '368352443079',
    projectId: 'pomodorable-26n09',
    authDomain: 'pomodorable-26n09.firebaseapp.com',
    storageBucket: 'pomodorable-26n09.appspot.com',
    measurementId: 'G-EZ2LM0TT3W',
  );
}
